FROM oven/bun:1.3-debian

WORKDIR /app

# Install dependencies
COPY package.json ./
RUN bun install --verbose

# Copy the rest of the application
COPY . .

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Run the development server
CMD ["bun", "run", "dev"]

